baseURL = "https://bammellab.github.io/"
title = "Bammellab"
languageCode = "en-us"
copyright = "Copyright 2020-2026 Jim Andreas"

# Default content language
defaultContentLanguage = "en"

# Enable emoji
enableEmoji = true

# Enable robots.txt generation
enableRobotsTXT = true

# Disable taxonomy pages
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
