baseURL = "https://bammellab.github.io/"
languageCode = "en-us"
title = "Bammellab"
theme = "Hugo-Octopress"
[pagination]
  pagerSize = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Jim Andreas"
  subtitle = "Visualization on the Android Platform"
  sidebar_about_description = "Exploring visualization design and tools aimed at Molecular Biology."
  sidebar_github = "https://github.com/bammellab"

[menu]
  [[menu.main]]
    name = "MotmBrowser"
    url = "/motm-browser/"
    weight = 1
  [[menu.main]]
    name = "SimpleMusicPlayer"
    url = "/simple-music-player/"
    weight = 2
  [[menu.main]]
    name = "GamepadTest"
    url = "/gamepad-test/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 7

copyright = "Copyright &copy; 2020 Jim Andreas"
